### ISSUE TITLE
Categories are missing from appstream data

### ISSUE THREAD

**Issue by bbhtt** [flathub/de.philippun1.Snoop#1]
This is due to the desktop file having a low quality category that is filtered by appstream
Please define a proper category from https://specifications.freedesktop.org/menu-spec/latest/apa.html

https://gitlab.gnome.org/philippun1/snoop/-/blob/cc27b12ea9e7f2734e15c17c1e39cbfd1192358b/data/de.philippun1.Snoop.desktop.in#L7

**Comment by philippun1** [comment]
Category is fixed now in the desktop file.
